Update CacheResponse.php
Biz-mark/Quicksilver pull request #6
Opened 2020-01-23 15:45 UTC by PubliAlex

Only cache pages for anonymous users

2020-02-04 13:35 UTC, FlusherDock1 commented on classes/middleware/CacheResponse.php
> +            && BackendAuth::getUser() == null
Use in this case BackendAuth::check()

2020-02-05 09:59 UTC, PubliAlex commented
Updated the PR by following your advice

2020-02-05 12:19 UTC, FlusherDock1 requested changes
`BackendAuth::check()` returns boolean value (true or false). Please change comparison from null to false. And i will merge it. Thanks

2020-02-05 12:30 UTC, PubliAlex commented
Done :)

2020-02-05 12:31 UTC, FlusherDock1 approved these changes

2020-02-05 12:32 UTC, merged